
import Proviedstore from "@/lib/proviedstore";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import Nave from "@/components/Nave";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html>
      <body>
        <Proviedstore>
          <Nave />
          {children}
          <Footer />
        </Proviedstore>
      </body>
    </html>


  );
}
